# Generated by Django 3.2.7 on 2022-07-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libra_rian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(default='', max_length=30, verbose_name='nic name')),
                ('status', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='librarian', max_length=12)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='consumer/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(default='', max_length=30, verbose_name='nic name')),
                ('status', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='member', max_length=12)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='member/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='member_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.member')),
            ],
        ),
        migrations.CreateModel(
            name='libra_rian_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('uzr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.libra_rian')),
            ],
        ),
    ]
