# Generated by Django 3.2.7 on 2022-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp',
            field=models.CharField(default='', max_length=200),
        ),
    ]
