# Generated by Django 3.2.7 on 2022-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220723_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='libra_rian',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
