# Generated by Django 3.2.7 on 2022-07-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220723_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_token',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='member_token',
        ),
    ]
