# Generated by Django 3.2.7 on 2022-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20220723_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='book_issue_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='book_returned_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
