# Generated by Django 3.2.7 on 2022-07-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220723_1801'),
        ('librarian', '0004_auto_20220723_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='accounts.libra_rian'),
        ),
    ]
