# Generated by Django 3.2.7 on 2022-07-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_auto_20220724_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='book_issue_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='book_returned_date',
            field=models.DateTimeField(default=''),
        ),
    ]
