# Generated by Django 3.2.7 on 2022-07-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0009_auto_20220724_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='book_issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='book_returned_date',
            field=models.DateTimeField(),
        ),
    ]
