# Generated by Django 3.2.7 on 2022-07-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220723_1801'),
        ('librarian', '0013_auto_20220724_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librarian', to='accounts.libra_rian'),
        ),
    ]
