# Generated by Django 3.2.7 on 2022-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0014_alter_book_detail_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizations',
            name='add_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='add_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='barrow_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='delete_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='remove_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='return_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorizations',
            name='view_member',
            field=models.BooleanField(default=False),
        ),
    ]
