# Generated by Django 3.2.7 on 2022-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0015_auto_20220724_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizations',
            name='add_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='add_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='barrow_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='delete_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='manage_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='remove_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='return_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='view_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='authorizations',
            name='view_member',
            field=models.BooleanField(default=True),
        ),
    ]
