# Generated by Django 3.2.7 on 2022-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220723_1801'),
        ('librarian', '0016_auto_20220724_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='book_used_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_used_by', to='accounts.libra_rian'),
        ),
        migrations.AlterField(
            model_name='book_detail',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=30),
        ),
    ]
