# Generated by Django 3.2.7 on 2022-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0017_auto_20220724_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_detail',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
